targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
      freezed:
        enabled: true
      json_serializable:
        enabled: true
      build_web_compilers|entrypoint:
        enabled: false
      graphql_codegen:
        options:
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/**/*.graphql
