fragment GalleryListData on Gallery {
  id
  title
  date
  rating100
  image_count
  details
  studio {
    id
    name
  }
  performers {
    id
    name
    image_path
  }
  files {
    path
  }
  paths {
    cover
  }
  cover {
    visual_files {
      ... on ImageFile {
        width
        height
      }
      ... on VideoFile {
        width
        height
      }
    }
  }
}

fragment GalleryDetailData on Gallery {
  ...GalleryListData
  code
  urls
  photographer
  organized
  created_at
  updated_at
  tags {
    id
    name
  }
  chapters {
    id
    title
    image_index
  }
}

query FindGalleries($filter: FindFilterType, $gallery_filter: GalleryFilterType) {
  findGalleries(filter: $filter, gallery_filter: $gallery_filter) {
    count
    galleries {
      ...GalleryListData
    }
  }
}

query FindGallery($id: ID!) {
  findGallery(id: $id) {
    ...GalleryDetailData
  }
}

mutation UpdateGalleryRating($id: ID!, $rating: Int!) {
  galleryUpdate(input: { id: $id, rating100: $rating }) {
    id
    rating100
  }
}
