display_name: StashFlow
package_name: stashflow
icon: asset/stashfluttericon.png
summary: A modern Flutter client app for browsing and managing your Stash library
vendor: StashFlow
packager: Alchemist Aloha
packager_email: kentclk@outlook.com
license: AGPL-3.0
url: https://github.com/Alchemist-Aloha/StashFlow
group: Applications/Video
categories:
  - Video
  - AudioVideo
generic_name: Stash client
startup_notify: true
