#!/usr/bin/env bash

set -euo pipefail

if (( $# != 2 )); then
  echo "Usage: $0 <artifact-version> <output-directory>" >&2
  exit 64
fi

artifact_version=$1
output_directory=$2
project_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
bundle_directory="$project_root/build/linux/x64/release/bundle"
package_root=$(mktemp -d)
trap 'rm -rf -- "$package_root"' EXIT

if [[ ! -x "$bundle_directory/StashFlow" ]]; then
  echo "Missing Linux release binary: $bundle_directory/StashFlow" >&2
  exit 1
fi

package_version=$(sed -n 's/^version: *//p' "$project_root/pubspec.yaml" | head -1)
if [[ -z "$package_version" ]]; then
  echo "Unable to read the package version from pubspec.yaml" >&2
  exit 1
fi

install -d \
  "$package_root/opt/StashFlow" \
  "$package_root/usr/bin" \
  "$package_root/usr/share/applications" \
  "$package_root/usr/share/icons/hicolor/256x256/apps"
cp -a "$bundle_directory/." "$package_root/opt/StashFlow/"
ln -s /opt/StashFlow/StashFlow "$package_root/usr/bin/stashflow"
install -Dm644 "$project_root/asset/stashfluttericon.png" \
  "$package_root/usr/share/icons/hicolor/256x256/apps/stashflow.png"

printf '%s\n' \
  '[Desktop Entry]' \
  'Name=StashFlow' \
  'GenericName=Stash client' \
  'Comment=A modern Flutter client for Stash' \
  'Exec=stashflow %U' \
  'Icon=stashflow' \
  'Terminal=false' \
  'Type=Application' \
  'StartupNotify=true' \
  'Categories=AudioVideo;Video;' \
  > "$package_root/usr/share/applications/stashflow.desktop"

installed_size=$(du -sb "$package_root/opt" "$package_root/usr" | awk '{ total += $1 } END { print total }')
build_date=${SOURCE_DATE_EPOCH:-$(date +%s)}

printf '%s\n' \
  '# Generated by scripts/build_linux_pacman.sh' \
  'pkgname = stashflow' \
  'pkgbase = stashflow' \
  "pkgver = $package_version-1" \
  'pkgdesc = A modern Flutter client app for browsing and managing your Stash library.' \
  'url = https://github.com/Alchemist-Aloha/StashFlow' \
  "builddate = $build_date" \
  'packager = Alchemist Aloha <Alchemist-Aloha@users.noreply.github.com>' \
  "size = $installed_size" \
  'arch = x86_64' \
  'license = AGPL-3.0' \
  'depend = gtk3' \
  'depend = libsecret' \
  > "$package_root/.PKGINFO"

(
  cd "$package_root"
  bsdtar -czf .MTREE \
    --format=mtree \
    --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
    --uid 0 --gid 0 --uname root --gname root \
    .PKGINFO opt usr
)

mkdir -p "$output_directory"
output_path="$output_directory/StashFlow-${artifact_version}-linux-x64.pkg.tar.zst"
(
  cd "$package_root"
  bsdtar -caf "$output_path" \
    --uid 0 --gid 0 --uname root --gname root \
    .PKGINFO .MTREE opt usr
)

echo "Built $output_path"
