display_name: StashFlow
package_name: stashflow
maintainer:
  name: Alchemist Aloha
  email: kentclk@outlook.com
section: video
priority: optional
installed_size: 120000
icon: asset/stashfluttericon.png
categories:
  - Video
  - AudioVideo
generic_name: Stash client
startup_notify: true
