name: Release APK

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Create Dummy Keystore for CI
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: |
          keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          echo "storePassword=android" > android/key.properties
          echo "keyPassword=android" >> android/key.properties
          echo "keyAlias=androiddebugkey" >> android/key.properties
          echo "storeFile=app/debug.keystore" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stash-app-flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
